Add ActiveRecord 7 compatibility
procore/sift pull request #60
Opened 2023-02-22 15:10 UTC by dervish86

Fix `NoMethodError: undefined method 'type_cast_from_user'` error that occurs when using Sift on Rails 7.

2023-02-22 15:57 UTC, kkohrt approved these changes
`gem_version` valid from [4.1.8 to 6.x](https://apidock.com/rails/v4.1.8/ActiveRecord/gem_version/class) and up [through 7.0.4.2](https://github.com/rails/rails/blob/v7.0.4.2/activerecord/lib/active_record/gem_version.rb) 👍

2023-02-23 15:43 UTC, joe-sharp approved these changes

2023-02-27 16:55 UTC, lessthanjacob approved these changes

2023-02-27 16:58 UTC, lessthanjacob requested changes
Apologies for requesting changes after adding an approval, but could we bump the version and add an entry to the `CHANGELOG`? Thanks!

2023-02-28 09:50 UTC, dervish86 commented
> Apologies for requesting changes after adding an approval, but could we bump the version and add an entry to the `CHANGELOG`? Thanks!

Sure, I have updated the CHANGELOG and bumped the version. @lessthanjacob could you help with releasing this update?

2023-03-02 17:07 UTC, dervish86 commented
Also, please note the ability to compare Gev::Version with string was added in RubyGems 3.3.6 https://github.com/rubygems/rubygems/blob/master/CHANGELOG.md#336--2022-01-26
If we want to support older versions of RubyGems we can wrap the string to Gem::Version or compare integers

2023-03-03 12:46 UTC, dervish86 commented
After investigation, I concluded that using the constant `VERSION` instead of `gem_version` would be better because the default version of RubyGems for Ruby 2.7 is 3.1.2. Updating RubyGems definitely good practice but I guess we shouldn't force it

2023-03-03 22:29 UTC, lessthanjacob approved these changes

2023-03-09 09:35 UTC, merged